/**
 * Factions — player (cartel) and AI gangs.
 * DealerFront mode: you command a faction, not a character.
 */

export interface Faction {
	id: number;
	name: string;
	color: string;
	isPlayer: boolean;
	/** Members (troops): the cartel's troop resource. */
	members: number;
	/** Product (stock generated by Labs, delivered). */
	product: number;
	/**
	 * Product still on the road (Lab → Storefront): produced but **not yet
	 * usable**. Only convoy arrivals move it into `product`.
	 */
	productInTransit: number;
	/** Dirty cash (unlaundered money), delivered. */
	dirtyCash: number;
	/**
	 * Dirty cash still on the road (Storefront → Front): sold but **not yet
	 * banked**. Interception can take it.
	 */
	dirtyInTransit: number;
	/** Clean cash (laundered money, base of the score). */
	cleanCash: number;
	/** Upgraded Housing (member production). */
	housing: number;
	/** Total buildings constructed. */
	buildings: number;
	/** Tech levels (Armament / Protection / Logistics). */
	tech: { armament: number; protection: number; logistics: number };
	/** Share of Members committed to each assault (0.05–0.6). */
	attackRatio: number;
	/** Share of Fronts' capacity actually laundered (0–1). */
	launderRatio: number;
	/** **Per-operation** cooldowns (ticks) — avoids the false choice. */
	strikeCooldown: number;
	raidCooldown: number;
	bustCooldown: number;
	interceptCooldown: number;
	/** Number of corruptions bought (increasing cost). */
	corruptionUses: number;
	/** Are Watchers paid this tick? (otherwise intel is blind). */
	guardsPaid: boolean;
	/** Is building upkeep paid this tick? (otherwise production ×0.5). */
	upkeepPaid: boolean;
	/** Current upkeep cost (Dirty cash/tick), recalculated each tick. */
	upkeep: number;
	/** End of the purchased armament window (tick) — temporary attack bonus. */
	armamentUntil: number;
	/** Purchased armament level (0 = none). */
	armamentLevel: number;
	/** Number of armament purchases (increasing cost). */
	armamentUses: number;
	/** Quarter buyout cooldown (ticks). */
	buyCooldown: number;
	/** Number of mercenary hires (increasing cost). */
	mercUses: number;
	/** Active contract: targeted gang (id) and contract end (tick). */
	contractTarget: number;
	contractUntil: number;
	/** Number of contracts paid (increasing cost). */
	contractUses: number;
	/** Quarters taken (any capture, neutral included). */
	captures: number;
	/** Quarters lost. */
	quartersLost: number;
	/** Gangs reduced to 0 quarters. */
	eliminations: number;
	/** Police raids suffered. */
	raidsSuffered: number;
	/** Police seizures suffered. */
	seizures: number;
	/** Faction reduced to 0 quarters. */
	eliminated: boolean;
	/** End of the traitor penalty (tick). */
	traitorUntil: number;
}

/** Faction palette (see docs/art-direction.md). */
export const FACTION_COLORS = [
	"#8FC7E8",
	"#E8C57A",
	"#8FD8A5",
	"#B79DE0",
	"#E88C80",
	"#6FD0C4",
] as const;

export const FACTION_NAMES = [
	"Cartel",
	"Northside Gang",
	"Eastside Gang",
	"Southside Gang",
	"Westside Gang",
	"Syndicate",
] as const;

/** Default number of factions (player + AI). */
export const FACTION_COUNT = 6;

export function createFactions(count: number, startMembers: number): Faction[] {
	const factions: Faction[] = [];
	for (let i = 0; i < count; i += 1) {
		factions.push({
			id: i,
			name: FACTION_NAMES[i % FACTION_NAMES.length]!,
			color: FACTION_COLORS[i % FACTION_COLORS.length]!,
			isPlayer: i === 0,
			members: startMembers,
			product: 0,
			productInTransit: 0,
			dirtyCash: 2000,
			dirtyInTransit: 0,
			cleanCash: 1000,
			housing: 0,
			buildings: 0,
			tech: { armament: 0, protection: 0, logistics: 0 },
			strikeCooldown: 0,
			raidCooldown: 0,
			bustCooldown: 0,
			interceptCooldown: 0,
			attackRatio: 0.2,
			launderRatio: 0.5,
			corruptionUses: 0,
			guardsPaid: true,
			upkeepPaid: true,
			upkeep: 0,
			armamentUntil: 0,
			armamentLevel: 0,
			armamentUses: 0,
			buyCooldown: 0,
			mercUses: 0,
			contractTarget: -1,
			contractUntil: 0,
			contractUses: 0,
			captures: 0,
			quartersLost: 0,
			eliminations: 0,
			raidsSuffered: 0,
			seizures: 0,
			eliminated: false,
			traitorUntil: 0,
		});
	}
	return factions;
}
