import { describe, expect, it } from "vitest";
import { BUILDING_INDEX, zoneBuildBonus, zoneTimeFactor } from "./buildings";
import { TICKS_PER_HOUR } from "./constants";
import { NEUTRAL } from "./territory";
import type { ZoneType } from "./types";
import { World } from "./world";

/** First neutral quarter (outside spawns). */
function firstNeutral(world: World): number {
	for (let i = 0; i < world.territory.count; i += 1) {
		if (world.territory.owner[i] === NEUTRAL) return i;
	}
	throw new Error("no neutral quarter");
}

/** Sells a fixed stock at a Storefront, for a given local wealth. */
function saleAt(wealth: number): number {
	const world = new World(1);
	const module = firstNeutral(world);
	world.territory.owner[module] = 1;
	world.territory.control[module] = 100;
	world.territory.building[module] = BUILDING_INDEX.storefront;
	world.city.demand[module] = 1;
	world.city.wealth[module] = wealth;
	const faction = world.factions[1]!;
	faction.product = 1000;
	faction.dirtyCash = 0;
	world.step();
	return faction.dirtyCash;
}

/** Member production for a given local demand (one Housing). */
function recruitmentAt(demand: number): number {
	const world = new World(1);
	const module = firstNeutral(world);
	world.territory.owner[module] = 1;
	world.territory.control[module] = 100;
	world.territory.building[module] = BUILDING_INDEX.housing;
	world.city.demand[module] = demand;
	world.step();
	return world.productionPerTick(1);
}

describe("local market", () => {
	it("sells higher in a wealthy quarter", () => {
		expect(saleAt(1.4)).toBeGreaterThan(saleAt(0.6));
	});

	it("recruits more in a high-demand quarter", () => {
		expect(recruitmentAt(1.3)).toBeGreaterThan(recruitmentAt(0.5));
	});

	it("stays deterministic (same seed, same result)", () => {
		expect(saleAt(1.0)).toBe(saleAt(1.0));
	});

	it("a Storefront without a Lab still sells (external supplier)", () => {
		const world = new World(1);
		const module = firstNeutral(world);
		world.territory.owner[module] = 1;
		world.territory.control[module] = 100;
		world.territory.building[module] = BUILDING_INDEX.storefront;
		world.city.demand[module] = 1;
		const faction = world.factions[1]!;
		faction.product = 0;
		faction.dirtyCash = 0;
		world.step();
		expect(faction.dirtyCash).toBeGreaterThan(0);
	});
});

/** First neutral quarter of the requested zone. */
function firstNeutralZone(world: World, zone: ZoneType): number {
	for (let i = 0; i < world.territory.count; i += 1) {
		if (world.territory.owner[i] === NEUTRAL && world.city.modules[i] === zone) return i;
	}
	throw new Error(`no neutral quarter of zone ${zone}`);
}

/** Product generated by a Lab depending on the quarter's zone. */
function labOutput(zone: ZoneType): number {
	const world = new World(1);
	const module = firstNeutralZone(world, zone);
	world.territory.owner[module] = 1;
	world.territory.control[module] = 100;
	world.territory.building[module] = BUILDING_INDEX.lab;
	const faction = world.factions[1]!;
	faction.product = 0;
	world.step();
	return faction.product;
}

describe("zone bonus", () => {
	it("industrial wasteland boosts Labs", () => {
		expect(labOutput("industrial")).toBeGreaterThan(labOutput("residential"));
	});

	it("residential boosts recruitment, not production", () => {
		expect(zoneBuildBonus("residential", "housing")).toBeGreaterThan(1);
		expect(zoneBuildBonus("residential", "lab")).toBe(1);
	});

	it("vacant lots have no bonus", () => {
		expect(zoneBuildBonus("vacant", "lab")).toBe(1);
		expect(zoneBuildBonus("vacant", "housing")).toBe(1);
	});
});

describe("rush hour", () => {
	it("night boosts nightlife, not day", () => {
		expect(zoneTimeFactor("nightlife", "storefront", 23)).toBeGreaterThan(1);
		expect(zoneTimeFactor("nightlife", "storefront", 11)).toBeLessThan(1);
	});

	it("commercial sells during the day", () => {
		expect(zoneTimeFactor("commercial", "storefront", 13)).toBeGreaterThan(
			zoneTimeFactor("commercial", "storefront", 1),
		);
	});

	it("average ~1 over the day (balance preserved)", () => {
		let sum = 0;
		for (let h = 0; h < 24; h += 1) sum += zoneTimeFactor("nightlife", "storefront", h);
		expect(sum / 24).toBeCloseTo(1, 1);
	});

	it("the clock advances with ticks", () => {
		const world = new World(1);
		const start = world.hourOfDay();
		for (let i = 0; i < TICKS_PER_HOUR; i += 1) world.step();
		expect(world.hourOfDay()).toBeCloseTo((start + 1) % 24, 3);
	});
});
